### ISSUE TITLE
Tightness of forecasted constraints

### ISSUE THREAD

**Issue by OSmotherly** [OSmotherly/LSST_mg_scale_forecasting#3]
The forecasted constraints for all parameters are a lot tighter than would be expected, indicating that something isn't quite right either with the derivative function or the actual forecasting process itself. This is likely to be something in the derivative vector construction process as there was previously a (now solved) issue with the degeneracy direction of the w_0-w_a parameter confidence interval.

**Comment by c-d-leonard** [comment]
@OSmotherly you can probably update what was wrong here and close?

**Comment by OSmotherly** [comment]
Issue has been solved - The order in which the power spectra effects were put together to form the data vector being used for construction of the Fisher matrix was not the same as the order in the covariance matrix used.

By switching around the data vector to contain cosmic shear, galaxy-galaxy lensing and then clustering power spectra (in that order) this issue has been resolved.
